### ISSUE TITLE
General layout improvements

### ISSUE THREAD

**Issue by andrewramsay** [NPLinker/nplinker-webapp#5]
The main webapp page with the tables and other widgets needs updating. There are some constraints imposed by the bokeh package and the way it handles widgets, but it should be possible to make the layout neater + more responsive to different screen sizes than it is at the moment.

**Comment by gcroci2** [comment]
We will develop a new dashboard from scratch, using another tech stack ([Plotly Dash](https://dash.plotly.com/)).
